### ISSUE TITLE
IE 11

### ISSUE THREAD

**Issue by alexsurg** [aurelia/polyfills#3]
Hi,

I have updated today to the latest version and since then IE11 stopped working for me.

i keep getting the following error (despite the fact that i dont use Symbol in my code):

Potentially unhandled rejection [1] ReferenceError: 'Symbol' is undefined
   at eachChar (Unknown script code:97:90)
   at addSegment (Unknown script code:492:5)
   at add (Unknown script code:235:9)
   at addRoute (Unknown script code:791:7)
   at Anonymous function (Unknown script code:465:11)
   at exportToRouter (Unknown script code:480:9)
   at Anonymous function (Unknown script code:714:9)
   at M (http://localhost:32433/jspm_packages/system-polyfills.js:4:8723)
   at H (http://localhost:32433/jspm_packages/system-polyfills.js:4:8310)
   at R.prototype.when (http://localhost:32433/jspm_packages/system-polyfills.js:4:12042)

I tried to add core-js to my code like you said in the last update but it didn't work.

Do you have any idea why this error happens and can you provide some working example of how we should add core js to the code.

Thanks,
Alex

**Comment by EisenbergEffect** [comment]
Please try running `jspm update` again and see if that fixes it for you. There were some patch releases to address these issues. In particular, the stack trace you are showing points to code that we fixed.

**Comment by alexsurg** [comment]
Thanks, the jspm update fixed it.
unfortunately now i get the following error:

Potentially unhandled rejection [3] TypeError: AMD module http://localhost:32433/jspm_packages/npm/aurelia-logging-console@1.0.0-beta.1.1.4.js did not define
   at Anonymous function (http://localhost:32433/jspm_packages/system.js:5:13182)
   at Anonymous function (http://localhost:32433/jspm_packages/system.js:5:15342)
   at Anonymous function (http://localhost:32433/jspm_packages/system.js:4:5964)
   at M (http://localhost:32433/jspm_packages/system-polyfills.js:4:8723)
   at H (http://localhost:32433/jspm_packages/system-polyfills.js:4:8310)
   at R.prototype.when (http://localhost:32433/jspm_packages/system-polyfills.js:4:12042)
   at b.prototype.run (http://localhost:32433/jspm_packages/system-polyfills.js:4:11076)
   at t.prototype._drain (http://localhost:32433/jspm_packages/system-polyfills.js:4:3014)
   at drain (http://localhost:32433/jspm_packages/system-polyfills.js:4:2681)
   at e (http://localhost:32433/jspm_packages/system-polyfills.js:4:4595)

Any idea why?

**Comment by EisenbergEffect** [comment]
I havent' seen that before. Try running `jspm dl-loader --latest` to make sure you have the latest version of the module loader.

**Comment by alexsurg** [comment]
Great running 'jspm dl-loader --latest' seems to fix it, also it changed the version of my core-js from 2.1.3 to 1.2.6 but i dont mind as long as it works.
